In [1]:
!pip install gensim

In [3]:
from gensim.models import Word2Vec

In [5]:
tokenized_sentences = [["Hello", "welcome", "to", "Data", "Science", "Program", "by", "Chetan"],
["Hello", "glad", "to", "have", "you", "here"],
["Hello", "welcome", "back"]]

In [11]:
model = Word2Vec(sentences=tokenized_sentences,min_count=1)

In [12]:
print(model)

Word2Vec<vocab=13, vector_size=100, alpha=0.025>


In [15]:
list(model.wv.index_to_key )

['Hello',
 'to',
 'welcome',
 'back',
 'here',
 'you',
 'have',
 'glad',
 'Chetan',
 'by',
 'Program',
 'Science',
 'Data']

In [22]:
model.wv.key_to_index

{'Hello': 0,
 'to': 1,
 'welcome': 2,
 'back': 3,
 'here': 4,
 'you': 5,
 'have': 6,
 'glad': 7,
 'Chetan': 8,
 'by': 9,
 'Program': 10,
 'Science': 11,
 'Data': 12}

In [23]:
model.wv.get_vector('Data')

array([-1.9442164e-03, -5.2675214e-03,  9.4471136e-03, -9.2987325e-03,
        4.5039477e-03,  5.4041781e-03, -1.4092624e-03,  9.0070926e-03,
        9.8853596e-03, -5.4750429e-03, -6.0210000e-03, -6.7469729e-03,
       -7.8948820e-03, -3.0479168e-03, -5.5940272e-03, -8.3446801e-03,
        7.8290224e-04,  2.9946566e-03,  6.4147436e-03, -2.6289499e-03,
       -4.4534765e-03,  1.2495709e-03,  3.9146186e-04,  8.1169987e-03,
        1.8280029e-04,  7.2315861e-03, -8.2645155e-03,  8.4335366e-03,
       -1.8889094e-03,  8.7011540e-03, -7.6168370e-03,  1.7963862e-03,
        1.0564864e-03,  4.6005251e-05, -5.1032533e-03, -9.2476979e-03,
       -7.2642174e-03, -7.9511739e-03,  1.9137275e-03,  4.7846674e-04,
       -1.8131376e-03,  7.1201660e-03, -2.4756920e-03, -1.3473093e-03,
       -8.9005642e-03, -9.9254129e-03,  8.9493981e-03, -5.7539381e-03,
       -6.3729975e-03,  5.1994072e-03,  6.6699935e-03, -6.8316413e-03,
        9.5975993e-04, -6.0084737e-03,  1.6473436e-03, -4.2892788e-03,
      

In [24]:
model.wv.get_vector('world')

KeyError: "Key 'world' not present"

In [25]:
model.wv.most_similar('Hello')

[('by', 0.21617142856121063),
 ('Data', 0.0931011214852333),
 ('glad', 0.09292754530906677),
 ('Science', 0.07963486760854721),
 ('Program', 0.06285078823566437),
 ('Chetan', 0.0270574688911438),
 ('have', 0.016134677454829216),
 ('to', -0.01083916611969471),
 ('here', -0.027750369161367416),
 ('welcome', -0.05234673246741295)]

### Use Pretrained Word2Vec model

In [26]:
import gensim

In [33]:
import gensim.downloader as api

pretrained_model = api.load("word2vec-google-news-300")

In [34]:
pretrained_model.most_similar('Hello')

[('Hi', 0.6188791394233704),
 ('Hello_hello', 0.603535532951355),
 ('Goodbye', 0.6006848216056824),
 ('Hiya', 0.5998829007148743),
 ('Hey', 0.5955355167388916),
 ('Bruce_Springsteen_bellowed', 0.5867887139320374),
 ('hello', 0.5842196941375732),
 ('Welcome', 0.5704931616783142),
 ('Hullo', 0.5693444609642029),
 ('@_ESPN_Michelle', 0.5587143898010254)]

In [35]:
pretrained_model.most_similar('Data')

[('data', 0.7262316346168518),
 ('Termed_Massively_Parallel', 0.5460323691368103),
 ('Data_System_IPEDS', 0.5428394079208374),
 ('Temperature_Maps', 0.5223192572593689),
 ('Analytics_Solution', 0.49304071068763733),
 ('Database', 0.4912521541118622),
 ('Partition_Master', 0.48701369762420654),
 ('QuickStudy', 0.48598507046699524),
 ('Geospatial_Data', 0.4815930426120758),
 ('Tweet_Sentiments_web', 0.4777469038963318)]

### Pre-trained GloVe Model

In [39]:
glove_model = api.load('glove-wiki-gigaword-50')

[==================================================] 100.0% 66.0/66.0MB downloaded


In [42]:
glove_model.most_similar('data')

[('information', 0.8329989314079285),
 ('tracking', 0.8124602437019348),
 ('database', 0.8122304677963257),
 ('analysis', 0.7966611981391907),
 ('applications', 0.792366623878479),
 ('indicate', 0.7726755142211914),
 ('indicates', 0.7607491612434387),
 ('computer', 0.7605311274528503),
 ('indicating', 0.7578965425491333),
 ('user', 0.7567423582077026)]

In [38]:
api.info()

{'corpora': {'semeval-2016-2017-task3-subtaskBC': {'num_records': -1,
   'record_format': 'dict',
   'file_size': 6344358,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/semeval-2016-2017-task3-subtaskB-eng/__init__.py',
   'license': 'All files released for the task are free for general research use',
   'fields': {'2016-train': ['...'],
    '2016-dev': ['...'],
    '2017-test': ['...'],
    '2016-test': ['...']},
   'description': 'SemEval 2016 / 2017 Task 3 Subtask B and C datasets contain train+development (317 original questions, 3,169 related questions, and 31,690 comments), and test datasets in English. The description of the tasks and the collected data is given in sections 3 and 4.1 of the task paper http://alt.qcri.org/semeval2016/task3/data/uploads/semeval2016-task3-report.pdf linked in section “Papers” of https://github.com/RaRe-Technologies/gensim-data/issues/18.',
   'checksum': '701ea67acd82e75f95e1d8e62fb0ad29',
   'file_name': 'se

### BERT - Glove

In [43]:
from flair.embeddings import WordEmbeddings, TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

In [44]:
glove_embedding = WordEmbeddings('glove')

In [48]:
sentence = Sentence("The founder of Apple is Steve Jobs")

In [49]:
glove_embedding.embed(sentence)

[Sentence[7]: "The founder of Apple is Steve Jobs"]

In [50]:
for token in sentence:
    print(token)
    print(token.embedding)
    print('-----------------------------')

Token[0]: "The"
tensor([-0.0382, -0.2449,  0.7281, -0.3996,  0.0832,  0.0440, -0.3914,  0.3344,
        -0.5755,  0.0875,  0.2879, -0.0673,  0.3091, -0.2638, -0.1323, -0.2076,
         0.3340, -0.3385, -0.3174, -0.4834,  0.1464, -0.3730,  0.3458,  0.0520,
         0.4495, -0.4697,  0.0263, -0.5415, -0.1552, -0.1411, -0.0397,  0.2828,
         0.1439,  0.2346, -0.3102,  0.0862,  0.2040,  0.5262,  0.1716, -0.0824,
        -0.7179, -0.4153,  0.2033, -0.1276,  0.4137,  0.5519,  0.5791, -0.3348,
        -0.3656, -0.5486, -0.0629,  0.2658,  0.3020,  0.9977, -0.8048, -3.0243,
         0.0125, -0.3694,  2.2167,  0.7220, -0.2498,  0.9214,  0.0345,  0.4674,
         1.1079, -0.1936, -0.0746,  0.2335, -0.0521, -0.2204,  0.0572, -0.1581,
        -0.3080, -0.4162,  0.3797,  0.1501, -0.5321, -0.2055, -1.2526,  0.0716,
         0.7056,  0.4974, -0.4206,  0.2615, -1.5380, -0.3022, -0.0734, -0.2831,
         0.3710, -0.2522,  0.0162, -0.0171, -0.3898,  0.8742, -0.7257, -0.5106,
        -0.5203, -0.1459

In [51]:
sentence_2 = Sentence("Apple is a Fruit")
glove_embedding.embed(sentence_2)

for token in sentence_2:
    print(token)
    print(token.embedding)
    print("-------------------------")

Token[0]: "Apple"
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.03

In [56]:
bert_embeddings = TransformerWordEmbeddings('bert-base-multilingual-cased')

In [57]:
bert_embeddings.embed(sentence)

[Sentence[7]: "The founder of Apple is Steve Jobs"]

In [58]:
for token in sentence:
    print(token)
    print(token.embedding)
    print('-----------------------')

Token[0]: "The"
tensor([-3.8194e-02, -2.4487e-01,  7.2812e-01, -3.9961e-01,  8.3172e-02,
         4.3953e-02, -3.9141e-01,  3.3440e-01, -5.7545e-01,  8.7459e-02,
         2.8787e-01, -6.7310e-02,  3.0906e-01, -2.6384e-01, -1.3231e-01,
        -2.0757e-01,  3.3395e-01, -3.3848e-01, -3.1743e-01, -4.8336e-01,
         1.4640e-01, -3.7304e-01,  3.4577e-01,  5.2041e-02,  4.4946e-01,
        -4.6971e-01,  2.6280e-02, -5.4155e-01, -1.5518e-01, -1.4107e-01,
        -3.9722e-02,  2.8277e-01,  1.4393e-01,  2.3464e-01, -3.1021e-01,
         8.6173e-02,  2.0397e-01,  5.2624e-01,  1.7164e-01, -8.2378e-02,
        -7.1787e-01, -4.1531e-01,  2.0335e-01, -1.2763e-01,  4.1367e-01,
         5.5187e-01,  5.7908e-01, -3.3477e-01, -3.6559e-01, -5.4857e-01,
        -6.2892e-02,  2.6584e-01,  3.0205e-01,  9.9775e-01, -8.0481e-01,
        -3.0243e+00,  1.2540e-02, -3.6942e-01,  2.2167e+00,  7.2201e-01,
        -2.4978e-01,  9.2136e-01,  3.4514e-02,  4.6745e-01,  1.1079e+00,
        -1.9358e-01, -7.4575e-02,  

In [59]:
bert_embeddings.embed(sentence_2)

[Sentence[4]: "Apple is a Fruit"]

In [60]:
for token in sentence_2:
    print(token)
    print(token.embedding)
    print('-----------------------')

Token[0]: "Apple"
tensor([-5.9850e-01, -4.6321e-01,  1.3001e-01, -1.9576e-02,  4.6030e-01,
        -3.0180e-01,  8.9770e-01, -6.5634e-01,  6.6858e-01, -4.9164e-01,
         3.7557e-02, -5.0889e-02,  6.4510e-01, -5.3882e-01, -3.7650e-01,
        -4.3120e-02,  5.1384e-01,  1.7783e-01,  2.8596e-01,  9.2063e-01,
        -4.9349e-01, -4.8583e-01,  6.1321e-01,  7.8211e-01,  1.9254e-01,
         9.1228e-01, -5.5596e-02, -1.2512e-01, -6.5688e-01,  6.8557e-02,
         5.5629e-01,  1.6110e+00, -7.3642e-03, -4.8879e-01,  4.5493e-01,
         9.6105e-01, -6.3369e-02,  1.7432e-01,  9.8140e-01, -1.3125e+00,
        -1.5801e-01, -5.4301e-01, -1.3888e-01, -2.6146e-01, -3.6910e-01,
         2.6844e-01, -2.4375e-01, -1.9484e-01,  6.2583e-01, -7.3770e-01,
         3.8351e-01, -7.5004e-01, -3.9053e-01,  9.1498e-02, -3.6591e-01,
        -1.4715e+00, -4.5228e-01,  2.2560e-01,  1.1412e+00, -3.8526e-01,
        -6.7160e-02,  5.7288e-01, -3.9191e-01,  3.1302e-01, -2.9235e-01,
        -9.6157e-01,  1.5154e-01,

In [62]:
import numpy as np

In [64]:
distance.euclidean(np.array(sentence[3].embedding),np.array(sentence_2[0].embedding)) ### GloVe Embedding Distance

11.783246040344238

In [65]:
sent_bert = bert_embeddings.embed(sentence)
sent_2_bert = bert_embeddings.embed(sentence_2)