# Why NumPy?

- Inorder to perform numerical operations like array addition, multiplication, create dummy values, etc.
- Its faster in python when we are dealing with numerical operations

In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1,2,3,4,5,6,7])
arr_1

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
type(arr_1)

numpy.ndarray

In [4]:
list_1 = [1,2,3,4,5,6,7]
type(list_1)

list

### List Vs Numpy Array
- In list, we cannot do element-wise operation directly but in array we can do that easily
- Array is homogenous datatype and list is heterogenous datatype.


#### Create 1D Array

In [6]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)
print('Dimention of Array  :', arr_1d.ndim)
print('No. of Elements     :',arr_1d.size)
print('Max Element Index   :', arr_1d.argmax())

[1 2 3 4 5]
Dimention of Array  : 1
No. of Elements     : 5
Max Element Index   : 4


#### Differences

In [7]:
list_1 = [1,2,3,4,5]
list_1.append(6)
list_1

[1, 2, 3, 4, 5, 6]

In [9]:
list_1 + 1

TypeError: can only concatenate list (not "int") to list

In [8]:
arr_1d = np.array([1,2,3,4,5])
arr_1d+1

array([2, 3, 4, 5, 6])

In [ ]:
list_2 = [1,2,3,"Chetan"]
print(list_2)
print(type(list_2))

[1, 2, 3, 'Chetan']
<class 'list'>


In [14]:
arr_2 = np.array([1,2,3,2.1])
arr_2

array([1. , 2. , 3. , 2.1])

#### Create 2D Array

In [19]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)
print('Dimention of Array  :', array_2d.ndim)
print('No. of Elements     :',array_2d.size)
print('Max Element Index   :', array_2d.argmax())

[[1 2 3 4]
 [5 6 7 8]]
Dimention of Array  : 2
No. of Elements     : 8
Max Element Index   : 7


#### Create 3D Array

In [25]:
array_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array_3d)
print('Dimention of Array  :', array_3d.ndim)
print('No. of Elements     :',array_3d.size)
print('Max Element Index   :', array_3d.argmax())
print('Type of elements    :',array_3d.dtype)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimention of Array  : 3
No. of Elements     : 9
Max Element Index   : 8
Type of elements    : int64


#### Convertion of DataType

In [27]:
array_3d_float = array_3d.astype('float')
print('Dimention of Array  :', array_3d_float.ndim)
print('Type of elements    :',array_3d_float.dtype)

Dimention of Array  : 3
Type of elements    : float64


#### Convertion of List to Array

In [28]:
list_3 = [[1,2,3,4],[5,6,7,8]]
print(list_3)
print(type(list_3))

[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>


In [29]:
# Conversion

list_to_array = np.array(list_3)
print(list_to_array)
print(type(list_to_array))
print(list_to_array.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


#### Convert Array to List Conversion

In [31]:
arr_4 = np.array([[1,2,3],[4,5,6]])
print(arr_4)
print(type(arr_4))
print('No. of Dimentions:', arr_4.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
No. of Dimentions: 2


In [34]:
array_to_list = arr_4.tolist()
print(array_to_list)
print(type(array_to_list))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>


### Statistical Operations

In [36]:
arr_6 = np.array([1,2,3,4,5,6,7,8,9,10])
arr_6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr_6.sum()

np.int64(55)

In [38]:
arr_6.prod()

np.int64(3628800)

In [39]:
arr_6.mean()

np.float64(5.5)

In [ ]:
arr_6.std() #From the center no./value, how much the datapoints are deviated

np.float64(2.8722813232690143)

In [41]:
arr_6.argmax()

np.int64(9)

### Reshaping

In [44]:
arr_7 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_7)
print('Dimentions :',arr_7.ndim)
print('Shape      :',arr_7.shape)

[[1 2 3 4]
 [5 6 7 8]]
Dimentions : 2
Shape      : (2, 4)


In [45]:
arr_7_reshape = arr_7.reshape((4,2))
print(arr_7_reshape)
print('Dimentions :',arr_7_reshape.ndim)
print('Shape      :',arr_7_reshape.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Dimentions : 2
Shape      : (4, 2)


In [47]:
arr_7_reshape_1d = arr_7.reshape((1,8))
print(arr_7_reshape_1d)
print('Dimentions :',arr_7_reshape_1d.ndim)
print('Shape      :',arr_7_reshape_1d.shape)

[[1 2 3 4 5 6 7 8]]
Dimentions : 2
Shape      : (1, 8)


In [48]:
arr_7_reshape_1d_flatten = arr_7.flatten()
print(arr_7_reshape_1d_flatten)
print('Dimentions :',arr_7_reshape_1d_flatten.ndim)
print('Shape      :',arr_7_reshape_1d_flatten.shape)

[1 2 3 4 5 6 7 8]
Dimentions : 1
Shape      : (8,)


### Sequencing, Repetition & Random Number Generation

In [50]:
np.arange(1,21,dtype='int')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
np.arange(1,21,dtype='float')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [52]:
np.linspace(start=1, stop=50,dtype='float',num=20)

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [55]:
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
np.ones((3,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
np.zeros((3,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [60]:
array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
array_2d.repeat(repeats=10,axis=1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [ ]:
# Generate Random Numbers

print(np.random.rand(10,10)) # always be in range of 0 to 1

[[0.14665725 0.9513555  0.94557399 0.72588964 0.35506662 0.3841664
  0.30371175 0.76963107 0.58743828 0.16628624]
 [0.60940054 0.34871247 0.10046076 0.44438438 0.8480408  0.81785049
  0.03131964 0.35604904 0.78268276 0.40682624]
 [0.71939305 0.7584006  0.76235997 0.16733063 0.08725154 0.74451073
  0.13745738 0.98957769 0.63280137 0.28722653]
 [0.98842236 0.81879495 0.28698095 0.00953164 0.57677389 0.75630286
  0.22404098 0.80888637 0.49472904 0.97794199]
 [0.82895183 0.89768649 0.27825897 0.25966798 0.99272452 0.74726738
  0.02972761 0.52548163 0.00999001 0.61101549]
 [0.74918392 0.59422459 0.410117   0.80680707 0.38508874 0.2968621
  0.12353798 0.58667247 0.11682976 0.46562096]
 [0.41750095 0.8664094  0.02250941 0.13187502 0.43234743 0.4318805
  0.54580341 0.70719837 0.5556171  0.94382261]
 [0.34988542 0.33767341 0.2590591  0.00467688 0.17660029 0.59545043
  0.88378798 0.43070019 0.95776329 0.03586822]
 [0.58980016 0.83595003 0.42781465 0.08691731 0.90422321 0.15095979
  0.13019821 0.

In [67]:
np.random.randint(low = 1, high=100,size=(10,1))

array([[42],
       [95],
       [25],
       [18],
       [30],
       [28],
       [75],
       [79],
       [15],
       [71]], dtype=int32)

In [77]:
lotter_list = [1,2,3,4,5,6,7,8,9,10]

In [80]:
np.random.choice(a= lotter_list, size=1)

array([2])

## Explore where function from Numpy